name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Add permissions needed for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IS_STATIC_EXPORT: false  # Set to 'true' if your Next.js app needs static export
      DEPLOYMENT_PACKAGE: './out'  # Adjust this based on your build output directory

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js application
      run: npm run build

    - name: Export for Static Sites (if applicable)
      run: npm run export
      if: ${{ env.IS_STATIC_EXPORT == 'true' }}  # Only runs if IS_STATIC_EXPORT is true

    - name: Debug Web App Name
      run: echo "Deploying to app: ${{ secrets.AZURE_WEBAPP_NAME }} in subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: ${{ env.DEPLOYMENT_PACKAGE }}
